### ISSUE TITLE
better JSX support

### ISSUE THREAD

**Issue by ghost** [MattDMo/neon-color-scheme-atom-syntax#2]
My second favorite syntax theme (after Behave) for Atom. It would be nice if there would be better support for React code (like differentiation between html tags and their attributes)

**Comment by MattDMo** [comment]
I'll see what I can do. Can you link me to the React syntax you use, as well as some detailed React files so I can test the changes?

**Comment by ghost** [comment]
This [repo  ](https://github.com/mattermost/platform/tree/master/web/react/components) has some nice code with ES6 syntax.
